export const rooms = [
    {
      hotelName: 'Luxury Resort',
      roomTierName: 'Deluxe Suite',
      price: 250,
      address: '123 Main Street, City',
      luxuryRating: 5,
      amenities: 8,
      averageRating: 4.5,
      numReviews: 50,
      image: 'https://example.com/image1.jpg',
    },
    {
      hotelName: 'Coastal Hotel',
      roomTierName: 'Ocean View Room',
      price: 180,
      address: '456 Beach Road, Town',
      luxuryRating: 4,
      amenities: 5,
      averageRating: 4.2,
      numReviews: 30,
      image: 'https://example.com/image2.jpg',
    },
    {
      hotelName: 'Mountain Lodge',
      roomTierName: 'Woodland Cabin',
      price: 120,
      address: '789 Forest Avenue, Village',
      luxuryRating: 3,
      amenities: 3,
      averageRating: 3.8,
      numReviews: 20,
      image: 'https://example.com/image3.jpg',
    },
    {
      hotelName: 'Urban Boutique',
      roomTierName: 'Executive Suite',
      price: 300,
      address: '101 City Center, Metropolitan',
      luxuryRating: 5,
      amenities: 10,
      averageRating: 4.9,
      numReviews: 100,
      image: 'https://example.com/image4.jpg',
    },
    {
      hotelName: 'Riverside Resort',
      roomTierName: 'Riverside Villa',
      price: 400,
      address: '222 River Road, Riverside',
      luxuryRating: 5,
      amenities: 7,
      averageRating: 4.7,
      numReviews: 80,
      image: 'https://example.com/image5.jpg',
    },
    {
        hotelName: 'Seaside Resort',
        roomTierName: 'Beachfront Bungalow',
        price: 280,
        address: '321 Ocean Avenue, Coastal City',
        luxuryRating: 4,
        amenities: 6,
        averageRating: 4.3,
        numReviews: 45,
        image: 'https://example.com/image6.jpg',
      },
      {
        hotelName: 'Historic Mansion',
        roomTierName: 'Presidential Suite',
        price: 500,
        address: '789 Heritage Street, Historic Town',
        luxuryRating: 5,
        amenities: 9,
        averageRating: 4.8,
        numReviews: 95,
        image: 'https://example.com/image7.jpg',
      },
      {
        hotelName: 'Ski Resort',
        roomTierName: 'Mountain View Chalet',
        price: 350,
        address: '555 Ski Slope Road, Snowy Village',
        luxuryRating: 4,
        amenities: 5,
        averageRating: 4.1,
        numReviews: 35,
        image: 'https://example.com/image8.jpg',
      },
      {
        hotelName: 'City Center Hotel',
        roomTierName: 'Cityscape Suite',
        price: 220,
        address: '777 Downtown Avenue, Urban City',
        luxuryRating: 3,
        amenities: 4,
        averageRating: 3.7,
        numReviews: 25,
        image: 'https://example.com/image9.jpg',
      },
      {
        hotelName: 'Lakefront Lodge',
        roomTierName: 'Lakeside Cabin',
        price: 180,
        address: '888 Lakeview Drive, Serene Lakeside',
        luxuryRating: 3,
        amenities: 3,
        averageRating: 3.5,
        numReviews: 15,
        image: 'https://example.com/image10.jpg',
      },
  ];
  